name: Build with Gradle

on:
  push:
    branches:
      - keyed-set-mode-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Check out mã nguồn từ repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Bước 2: Thiết lập JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Skript
      run: git submodule update --init
    # Bước 3: Thực hiện build với Gradle
    - name: Build with Gradle
      run: ./gradlew clean build

    # Bước 4: Lưu trữ artifact (file .jar)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/*.jar
